[build]
  command = "./node_modules/gulp/bin/gulp build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301

[build.processing]
  css = "minify"
  js = "minify"
  images = "optimize"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
